### ISSUE TITLE
ambient light sensor for brightness control

### ISSUE THREAD

**Issue by pluschris** [bigdisp/scoreboard-hardware#9]

**Comment by gn36** [comment]
This could potentially be realized as a secondary master on the i2c bus, sending broadcasts to all digits. 

But probably it is best to have all control logic in one place and use the raspi for the control and either realize this directly with the raspi in some way (e.g. an astable setup with a NE555 counter with an ldr and interval counting on one of the gpio pins of the raspi or something similar)

Also, I would see this as nice to have, not as a requirement, really. The board will work fine even if it is not dimmed when it is dark.

**Comment by pluschris** [comment]
That's why I didn't set the "First Release"-Milestone. If the score-board is running, we can add an extension board.
